version: '3.8'

services:
  db-local:
    image: postgres:15-alpine
    container_name: todolist-db-local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Aqui acontece a "mágica" do volume