spring.application.name=todolist

# Configuração para o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/todolist?createDatabaseIfNotExist=true
spring.datasource.username=todolist
spring.datasource.password=todolist

# Driver oficial
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Opcional: Melhora a formatação do SQL no console para você debugar
spring.jpa.properties.hibernate.format_sql=true