spring.application.name=todolist
spring.datasource.url=jdbc:postgresql://dpg-d6iqbpnkijhs738b3gr0-a:5432/todolist_56nr
spring.datasource.username=todolist
spring.datasource.password=afWefufrsp1SO24Q6hOK9aXs0JMa5pTB
spring.datasource.driver-class-name=org.postgresql.Driver
# Dialeto para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

todolist.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
todolist.jwtExpirationMs=86400000